<a href="https://colab.research.google.com/github/ShraddhaBShinde/intro/blob/main/Logistic_Regression_Classifier_with_Artificial_Generated.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

**Importing Libraries**

In [2]:
import pandas as pd

In [3]:
import numpy as np

In [4]:
import matplotlib.pyplot as plt

**Generating Dataset**

In [5]:
from sklearn.datasets import make_classification

In [6]:
#with coefficient of underlined model return
X, y = make_classification(n_samples=1000, n_features=5, n_clusters_per_class=1, n_classes=2, random_state=2529)

**Getting the first five rows of target variable(y) and features(x)**

In [7]:
X[0:5]

array([[ 1.54701705,  0.84770596, -0.41725021, -0.62356778, -0.19388577],
       [ 0.80633556,  0.40985594, -0.45641095, -0.3052022 ,  0.50935923],
       [ 0.94390268,  0.70041038,  1.11385452, -0.49394417,  1.42305455],
       [ 1.92091517,  0.95815739, -1.2235022 , -0.71578154,  0.66588981],
       [ 1.45270369,  0.69035375, -1.18119669, -0.52009219, -0.22745417]])

In [8]:
y[0:5]

array([0, 0, 1, 0, 0])

**Getting the shape of DataFrame**

In [9]:
X.shape, y.shape

((1000, 5), (1000,))

**Getting the Train Test Split**

In [11]:
from sklearn.model_selection import train_test_split

In [12]:
X_train, X_test, y_train, y_test= train_test_split(X,y, test_size=0.3, random_state=2529)

In [13]:
X_train.shape, X_test.shape, y_train.shape, y_test.shape

((700, 5), (300, 5), (700,), (300,))

**Getting Logistic Regression Classification Model Train**

In [14]:
from sklearn.linear_model import LogisticRegression

In [15]:
model=LogisticRegression()

In [16]:
model.fit(X_train, y_train)

LogisticRegression()

**Getting model prediction**

In [17]:
y_pred= model.predict(X_test)

In [18]:
y_pred.shape

(300,)

In [19]:
y_pred

array([1, 0, 0, 0, 1, 1, 0, 1, 1, 0, 1, 0, 1, 0, 0, 1, 1, 0, 1, 1, 0, 1,
       0, 0, 1, 1, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 1, 1, 1, 1, 1, 1, 1, 0,
       0, 1, 1, 0, 0, 0, 1, 0, 1, 0, 1, 0, 1, 1, 1, 0, 0, 1, 0, 0, 0, 0,
       1, 0, 0, 1, 1, 1, 0, 1, 1, 0, 0, 0, 0, 0, 0, 1, 0, 1, 0, 0, 1, 0,
       0, 0, 0, 1, 0, 0, 1, 1, 1, 1, 0, 0, 1, 0, 1, 1, 0, 0, 1, 0, 1, 1,
       0, 0, 1, 1, 1, 1, 0, 1, 0, 0, 0, 1, 0, 0, 1, 0, 0, 1, 1, 1, 0, 0,
       1, 0, 1, 0, 1, 1, 0, 1, 1, 1, 0, 1, 0, 1, 1, 0, 0, 1, 1, 1, 0, 1,
       0, 0, 1, 0, 0, 1, 1, 0, 0, 1, 1, 0, 1, 0, 0, 0, 0, 1, 0, 1, 0, 1,
       1, 1, 1, 0, 0, 0, 0, 0, 1, 0, 1, 0, 1, 1, 0, 0, 0, 0, 0, 0, 1, 1,
       0, 0, 1, 0, 1, 0, 0, 1, 0, 0, 1, 1, 0, 1, 1, 0, 0, 1, 0, 0, 0, 0,
       1, 1, 0, 1, 1, 1, 0, 1, 1, 1, 0, 0, 1, 0, 1, 1, 1, 0, 1, 1, 0, 1,
       0, 0, 1, 1, 1, 0, 1, 0, 0, 0, 1, 1, 1, 1, 0, 1, 0, 1, 0, 1, 0, 0,
       0, 0, 0, 1, 1, 0, 0, 1, 0, 1, 0, 0, 0, 1, 1, 1, 0, 1, 0, 0, 0, 0,
       1, 0, 0, 0, 1, 1, 1, 0, 1, 0, 1, 0, 0, 1])

**Getting model evaluation**

In [20]:
from sklearn.metrics import accuracy_score, confusion_matrix, classification_report

In [21]:
accuracy_score(y_test,y_pred)

0.99

In [22]:
confusion_matrix(y_test,y_pred)

array([[156,   1],
       [  2, 141]])

In [23]:
print(classification_report(y_test,y_pred))

              precision    recall  f1-score   support

           0       0.99      0.99      0.99       157
           1       0.99      0.99      0.99       143

    accuracy                           0.99       300
   macro avg       0.99      0.99      0.99       300
weighted avg       0.99      0.99      0.99       300



**Hyperparameter Tunning: Grid Search**

In [31]:
from sklearn.model_selection import GridSearchCV
parameters={'penalty': ['l1','l2'],'C':[0.001,.009,0.01,.09,1,5,10,25], 'solver':['liblinear']}
gridsearch = GridSearchCV(LogisticRegression(), parameters)
gridsearch.fit(X_train, y_train)

GridSearchCV(estimator=LogisticRegression(),
             param_grid={'C': [0.001, 0.009, 0.01, 0.09, 1, 5, 10, 25],
                         'penalty': ['l1', 'l2'], 'solver': ['liblinear']})

In [32]:
gridsearch.best_params_

{'C': 1, 'penalty': 'l1', 'solver': 'liblinear'}

In [33]:
gridsearch.best_score_

0.9914285714285714

In [34]:
gridsearch.best_estimator_

LogisticRegression(C=1, penalty='l1', solver='liblinear')

In [35]:
gridsearch.best_index_

8

In [36]:
y_pred_grid= gridsearch.predict(X_test)

In [38]:
confusion_matrix(y_test, y_pred_grid)

array([[156,   1],
       [  2, 141]])

In [39]:
print(classification_report(y_test, y_pred_grid))

              precision    recall  f1-score   support

           0       0.99      0.99      0.99       157
           1       0.99      0.99      0.99       143

    accuracy                           0.99       300
   macro avg       0.99      0.99      0.99       300
weighted avg       0.99      0.99      0.99       300

